# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://uts-tops-math-competition.github.io/'
baseurl: ''
title: 'UTMC'
description: 'UTS-TOPS Math Competition'
permalink: pretty
logo: "/images/UTMC-Navy-Cropped.png"
reg-link: "https://utmc.typeform.com/to/mHTwSg"
email: "utmcstaff@gmail.com"

# Header nav
navigation_header:
- title: Home
  url: /
- title: Rules
  url: /rules/
- title: Archive
  url: /archive/
- title: Staff
  url: /staff/

