# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://uts-tops-math-competition.github.io/'
baseurl: ''
title: 'UTMC'
description: 'UTS-TOPS Math Competition'
permalink: pretty
logo: "/images/UTMC-logo1.png"

# Header nav
navigation_header:
- title: Home
  url: /

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
